---
-   name: Instalação do Firefox
    hosts: localhost
    gather_facts: no
    become: true

    tasks:
        -   name: Create a directory if it does not exist
            ansible.builtin.file:
                path: /opt/firefox-developer
                state: directory
                mode: '0755'
    
        -   name: Extraindo Firefox
            ansible.builtin.unarchive:
                remote_src: yes
                src: https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=pt-BR
                dest: /opt/firefox-developer/

        -   name: Disponibilizando binário do Firefox para usuários
            ansible.builtin.file:
                src: /opt/firefox-developer/firefox
                dest: /usr/local/bin/firefox-developer
                owner: nobody
                group: nogroup
                state: link

        -   name: Adicionando Firefox nas aplicações
            ansible.builtin.file:
                src: ../../configuracoes/firefox-developer.desktop
                dest: /usr/share/applications/firefox-developer.desktop
                owner: nobody
                group: nogroup
                state: link
