---
-   name: Instalação do Oh My SH
    hosts: localhost
    gather_facts: no
    become: true

    tasks:
        -   name: Instalando
            ansible.builtin.command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"