---
-   name: Instalação do Spotify
    hosts: localhost
    gather_facts: no
    become: true

    tasks:
        -   name: Baixar chave GPG do Spotify
            ansible.builtin.get_url:
                url: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
                dest: /tmp/spotify.gpg

        -   name: Converter chave para formato gpg e mover para trusted.gpg.d
            ansible.builtin.command:
                cmd: gpg --dearmor -o /etc/apt/trusted.gpg.d/spotify.gpg /tmp/spotify.gpg
            args:
                creates: /etc/apt/trusted.gpg.d/spotify.gpg

        -   name: Adicionar repositório do Spotify
            ansible.builtin.apt_repository:
                repo: 'deb https://repository.spotify.com stable non-free'
                filename: spotify
                state: present
    
        -   name: Instalando Spotify
            ansible.builtin.apt:
                name: spotify-client
                state: present
                update_cache: yes
