---
-   name: Instalar Sublime Text
    hosts: localhost
    become: true
    vars:
        sublime_key_url: "https://download.sublimetext.com/sublimehq-pub.gpg"
        sublime_key_dest: "/etc/apt/keyrings/sublimehq-pub.asc"
        sublime_sources_file: "/etc/apt/sources.list.d/sublime-text.sources"

    tasks:
        -   name: Garantir que /etc/apt/keyrings exista
            ansible.builtin.file:
                path: /etc/apt/keyrings
                state: directory
                mode: '0755'

        -   name: Baixar chave GPG do Sublime
            ansible.builtin.get_url:
                url: "{{ sublime_key_url }}"
                dest: "{{ sublime_key_dest }}"
                mode: '0644'

        -   name: Adicionar arquivo de repositório do Sublime
            ansible.builtin.copy:
                dest: "{{ sublime_sources_file }}"
                content: |
                    Types: deb
                    URIs: https://download.sublimetext.com/
                    Suites: apt/stable/
                    Signed-By: /etc/apt/keyrings/sublimehq-pub.asc
                mode: '0644'

        -   name: Instalar sublime-text
            ansible.builtin.apt:
                update_cache: yes
                name: sublime-text
                state: present
