#!/bin/bash

# Propósito: instalar dependências e scripts
# Uso: sudo ./instalar

source "$(realpath $(dirname $0))/utilitarios/logs"

read -r -s -p "Informe a senha sudo do usuário para o Ansible: " SENHA_SUDO
echo
read -r -s -p "Informe novamente: " REPETE_SENHA_SUDO
echo

if [[ "$REPETE_SENHA_SUDO" != "$SENHA_SUDO" ]]; then

	SENHA_SUDO=""
	REPETE_SENHA_SUDO=""
	unset SENHA_SUDO
	unset REPETE_SENHA_SUDO

	erro "Senhas não conferem!!!"
	exit 1
fi

#"$(realpath $(dirname $0))/atualizacoes/atualizar"

sudo apt update -y

info "Instalando pré-requisitos..."
rodarComando sudo apt install -y software-properties-common

info "Adicionando PPA do próprio ansible"
rodarComando sudo add-apt-repository --yes ppa:ansible/ansible

info "Atualizando pacotes"
rodarComando sudo apt update -y

info "Instalando Ansible"
rodarComando sudo apt install -y ansible

info "Verificando instalação do Ansible..."
if command -v ansible >/dev/null 2>&1; then
	sucesso "Ansible instalado com sucesso"
else
	erro "'ansible' não encontrado após instalação. Revise os passos anteriores." >&2
	exit 2
fi

info "Instalando dependências com Ansible"
printf '{"ansible_become_pass":"%s"}\n' "$SENHA_SUDO" | \
  ansible-playbook "$(realpath $(dirname $0))/desktop.yml" --extra-vars -

SENHA_SUDO=""
unset SENHA_SUDO
