---
-   name: Configurações para o Cinnamon
    hosts: localhost
    gather_facts: no

    tasks:
        -   name: Aceita volume de sons amplificado
            ansible.builtin.command: |
                gsettings set org.cinnamon.desktop.sound allow-amplified-volume true

        -   name: Definindo modo escuro com detalhes em laranja
            ansible.builtin.command: |
                gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-Y-Dark-Orange'

        -   name: Exibindo arquivos ocultos no Nemo
            ansible.builtin.command: |
                gsettings set org.nemo.preferences show-hidden-files true

        -   name: Bloqueio imediato ao iniciar proteção de tela
            ansible.builtin.command: |
                gsettings set org.cinnamon.desktop.screensaver lock-enabled true

        -   name: Iniciando protetor de tela após 5 minutos de inatividade
            ansible.builtin.command: |
                gsettings set org.cinnamon.desktop.session idle-delay 300