---
-   name: Configurações para o Cinnamon
    hosts: localhost
    gather_facts: no

    tasks:
        -   name: Aceita volume de sons amplificado
            ansible.builtin.command: |
                gsettings set org.cinnamon.desktop.sound allow-amplified-volume true

        -   name: Definindo modo escuro com detalhes em laranja
            ansible.builtin.command: |
                gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-Y-Dark-Orange'