---
-   name: Configurações de data e hora
    hosts: localhost
    gather_facts: no
    become: true

    vars:
        applet_file: "/home/{{ usuario_sistema }}/.config/cinnamon/spices/calendar@cinnamon.org/13.json"
        custom_format: "%a, %e/%m %b, %H:%M:%S"
        custom_tooltip_format: "%A, %e/%m/%Y, %B, %H:%M:%S"
        backup_suffix: ".ansible.bkp"

    tasks:
        -   name: Verifica se o arquivo existe
            ansible.builtin.stat:
                path: "{{ applet_file }}"
            register: file_stat

        -   name: Falhar se o arquivo não existir
            ansible.builtin.fail:
                msg: "Arquivo {{ applet_file }} não encontrado."
            when: not file_stat.stat.exists

        -   name: Verifica se o arquivo de backup existe
            ansible.builtin.stat:
                path: "{{ applet_file }}{{ backup_suffix }}"
            register: app_file_backup

        -   name: Fazer backup do {{ applet_file }} (apenas se ainda não existir backup)
            ansible.builtin.copy:
                src: "{{ applet_file }}"
                dest: "{{ applet_file }}{{ backup_suffix }}"
                remote_src: yes
                owner: root
                group: root
                mode: '0644'
            when: not (app_file_backup is defined and app_file_backup.stat.exists)
            vars:
                app_file_backup: "{{ lookup('ansible.builtin.stat', applet_file + backup_suffix, wantlist=False) }}"
            ignore_errors: yes

        -   name: Ler {{ applet_file }}
            ansible.builtin.slurp:
                path: "{{ applet_file }}"
            register: slurped

        -   name: Decodificar e converter para objeto JSON
            set_fact:
                schema_obj: "{{ (slurped.content | b64decode) | from_json }}"

        -   name: Ajustar apenas os campos value desejados (em memória)
            set_fact:
                new_schema_obj: >-
                    {{ schema_obj | combine({
                         'custom-format': (schema_obj['custom-format'] | default({}) ) | combine({'value': custom_format}),
                         'custom-tooltip-format': (schema_obj['custom-tooltip-format'] | default({}) ) | combine({'value': custom_tooltip_format}),
                         'use-custom-format': (schema_obj['use-custom-format'] | default({}) ) | combine({'value': true})
                       }, recursive=True) }}

        -   name: Assegurar que o novo objeto JSON foi gerado
            ansible.builtin.assert:
                that:
                    - new_schema_obj is defined
                    - new_schema_obj['custom-format']['value'] == custom_format
                    - new_schema_obj['custom-tooltip-format']['value'] == custom_tooltip_format
                    - new_schema_obj['use-custom-format']['value'] == true

        -   name: Escrever novo arquivo {{ applet_file }}
            ansible.builtin.copy:
                content: "{{ new_schema_obj | to_nice_json }}"
                dest: "{{ applet_file }}"
                owner: root
                group: root
                mode: '0644'
                backup: yes
